# Plugin configuration file for ${name} v${version}

# localized language support
language: en-US

# Locale (used for time and number formatting)
locale: en-US

# Timezone (uses system default if not set. valid tz identifiers listed here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List)
#timezone: America/Chicago

# enabled worlds list
# if this list is empty, all worlds will be added to the enabled worlds list
# otherwise, only listed worlds will be added to the enabled worlds list

enabled-worlds: []
#  - enabled_world1
#  - enabled_world2

# disabled worlds list
# these worlds will be removed from the enabled worlds list created by the previous setting

disabled-worlds:
  - disabled_world1
  - disabled_world2

# Destroy compass when dropped by player
destroy-on-drop: true

# Prevent placing death compass in chests or other containers
prevent-storage: true

# delay setting compass target after respawn (in ticks; 20 ticks = 1 second)
target-delay: 20

# play sound effects
sound-effects: true
